apiVersion: v1
kind: Secret
metadata:
  name: {{ include "task-manager.fullname" . }}-secrets
  labels:
    {{- include "task-manager.labels" . | nindent 4 }}
type: Opaque
stringData:
  jwt-secret: {{ .Values.secrets.jwtSecret | required "secrets.jwtSecret is required" | quote }}
  db-user: {{ .Values.secrets.dbUser | quote }}
  db-password: {{ .Values.secrets.dbPassword | required "secrets.dbPassword is required" | quote }}
  db-name: {{ .Values.secrets.dbName | quote }}
  db-host: {{ .Values.secrets.dbHost | quote }}
  db-port: {{ .Values.secrets.dbPort | quote }}
  api-username: {{ .Values.secrets.apiUsername | quote }}
  api-password: {{ .Values.secrets.apiPassword | required "secrets.apiPassword is required" | quote }}
