apiVersion: v2
name: task-manager
description: Task Manager REST API - Helm Chart
type: application
version: 0.2.0
appVersion: "1.0.0"
keywords:
  - task-manager
  - rest-api
  - go
maintainers:
  - name: IaSEncore
